ALTER TABLE notes ADD COLUMN status TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE notes ADD COLUMN priority TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE notes ADD COLUMN due_date TEXT;
ALTER TABLE notes ADD COLUMN blocks TEXT NOT NULL DEFAULT '';
